# Generated by Django 3.1.6 on 2021-02-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='products',
            name='Price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
