# Generated by Django 3.1.6 on 2021-02-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protect', '0002_auto_20210203_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='static/image'),
        ),
    ]
