# Generated by Django 3.1.6 on 2021-02-03 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protect', '0004_auto_20210203_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='protect.category'),
            preserve_default=False,
        ),
    ]
